   SELECT FP.PRODUCT_ID
          , FP.PRODUCT_NAME
          , SUM(FP.PRICE * FO.AMOUNT) AS TOTAL_SALES
     FROM FOOD_PRODUCT FP
LEFT JOIN FOOD_ORDER FO
       ON FP.PRODUCT_ID = FO.PRODUCT_ID
      AND FO.PRODUCE_DATE BETWEEN DATE '2022-05-01' AND DATE '2022-05-31'
    WHERE FP.PRICE * FO.AMOUNT > 0
 GROUP BY FP.PRODUCT_ID
          , FP.PRODUCT_NAME
 ORDER BY TOTAL_SALES DESC
          , FP.PRODUCT_ID ASC
;
