  SELECT DISTINCT I.REST_ID
         , I.REST_NAME
         , I.FOOD_TYPE
         , I.FAVORITES
         , I.ADDRESS
         , ROUND(AVG(R.REVIEW_SCORE) OVER (PARTITION BY I.REST_ID), 2) SCORE
    FROM REST_INFO I
    JOIN REST_REVIEW R 
      ON I.REST_ID = R.REST_ID
   WHERE SUBSTR(I.ADDRESS, 1, 2) = '서울'
ORDER BY SCORE DESC,
         FAVORITES DESC
;
