WITH MAXPRICE AS(
      SELECT CATEGORY, 
             MAX(PRICE) MAX_PRICE
        FROM FOOD_PRODUCT
    GROUP BY CATEGORY
      HAVING CATEGORY IN ('과자', '국', '김치', '식용유')
)
  SELECT FP.CATEGORY, 
         MP.MAX_PRICE, 
         FP.PRODUCT_NAME
    FROM FOOD_PRODUCT FP
    JOIN MAXPRICE MP 
      ON FP.CATEGORY = MP.CATEGORY 
         AND FP.PRICE = MP.MAX_PRICE
ORDER BY MP.MAX_PRICE DESC
;
