   SELECT DISTINCT CP1.CART_ID
     FROM CART_PRODUCTS CP1
    WHERE CP1.NAME = 'Milk'
INTERSECT
   SELECT DISTINCT CP2.CART_ID
     FROM CART_PRODUCTS CP2
    WHERE CP2.NAME = 'Yogurt'
 ORDER BY CART_ID
;
