WITH MILK_CART AS(
    SELECT DISTINCT CART_ID
      FROM CART_PRODUCTS
     WHERE NAME = 'Milk'
), 
YOGURT_CART AS(
    SELECT DISTINCT CART_ID
      FROM CART_PRODUCTS
     WHERE NAME = 'Yogurt'
)
  SELECT MC.CART_ID
    FROM MILK_CART MC
    JOIN YOGURT_CART YC
      ON MC.CART_ID = YC.CART_ID
ORDER BY MC.CART_ID
;
