WITH LEVEL_CONDITION AS
(
        SELECT LEVEL-1 LEV
          FROM DUAL
    CONNECT BY LEVEL <= 24
), 
COUNT_CONDITION AS
(
      SELECT TO_CHAR(DATETIME, 'FMHH24') HOUR
             , COUNT(*) COUNT
        FROM ANIMAL_OUTS
    GROUP BY TO_CHAR(DATETIME, 'FMHH24')    
)
    SELECT L.LEV
           , NVL(C.COUNT, 0) COUNT
      FROM COUNT_CONDITION C
RIGHT JOIN LEVEL_CONDITION L
        ON C.HOUR = L.LEV
  ORDER BY L.LEV
;
