  SELECT A.AUTHOR_ID
         , A.AUTHOR_NAME
         , B.CATEGORY
         , SUM(BS.SALES * B.PRICE) TOTAL_SALES
    FROM BOOK B
    JOIN AUTHOR A
      ON B.AUTHOR_ID = A.AUTHOR_ID
    JOIN BOOK_SALES BS
      ON B.BOOK_ID = BS.BOOK_ID
   WHERE TRUNC(SALES_DATE, 'MM') = TO_DATE('2022-01-01', 'YYYY-MM-DD')
GROUP BY A.AUTHOR_ID
         , A.AUTHOR_NAME
         , B.CATEGORY
ORDER BY A.AUTHOR_ID ASC
         , B.CATEGORY DESC
;
