WITH CONDITIONS AS (
    SELECT *
      FROM MEMBER_PROFILE
     WHERE TLNO IS NOT NULL
       AND EXTRACT(MONTH FROM DATE_OF_BIRTH) = 3
       AND GENDER = 'W'
)
  SELECT MEMBER_ID, 
         MEMBER_NAME, 
         GENDER, 
         TO_CHAR(DATE_OF_BIRTH, 'YYYY-MM-DD') DATE_OF_BIRTH
    FROM CONDITIONS
ORDER BY MEMBER_ID ASC
;
