  SELECT DISTINCT PRODUCT_CODE,
         SUM(O.SALES_AMOUNT * P.PRICE) OVER (PARTITION BY PRODUCT_CODE) AS SALES
    FROM PRODUCT P
    JOIN OFFLINE_SALE O
      ON P.PRODUCT_ID = O.PRODUCT_ID
ORDER BY SALES DESC, 
         PRODUCT_CODE
;
