 SELECT DISTINCT II.INGREDIENT_TYPE, 
         SUM(FH.TOTAL_ORDER) OVER (PARTITION BY II.INGREDIENT_TYPE) TOTAL_ORDER
    FROM FIRST_HALF FH
    JOIN ICECREAM_INFO II
      ON FH.FLAVOR=II.FLAVOR
ORDER BY TOTAL_ORDER
;
