WITH JOINTABLE AS(
    SELECT II.INGREDIENT_TYPE, 
           FH.TOTAL_ORDER
      FROM FIRST_HALF FH
      JOIN ICECREAM_INFO II
        ON FH.FLAVOR=II.FLAVOR
)
  SELECT INGREDIENT_TYPE, 
         SUM(TOTAL_ORDER)
    FROM JOINTABLE
GROUP BY INGREDIENT_TYPE
ORDER BY SUM(TOTAL_ORDER)
;
