  SELECT DISTINCT USER_ID,
         PRODUCT_ID
    FROM (
      SELECT USER_ID,
             PRODUCT_ID,
             COUNT(*) OVER (PARTITION BY USER_ID, PRODUCT_ID) AS COUNT_PRODUCT
        FROM ONLINE_SALE
    )
   WHERE COUNT_PRODUCT > 1
ORDER BY USER_ID,
         PRODUCT_ID DESC
;
