WITH TOTAL AS(
    SELECT B.BOOK_ID,
           A.AUTHOR_NAME,
           B.PUBLISHED_DATE, 
           B.CATEGORY
      FROM BOOK B
      JOIN AUTHOR A
        ON B.AUTHOR_ID=A.AUTHOR_ID
)
  SELECT BOOK_ID, 
         AUTHOR_NAME, 
         TO_CHAR(PUBLISHED_DATE, 'YYYY-MM-DD') PUBLISHED_DATE
    FROM TOTAL
   WHERE CATEGORY='경제'
ORDER BY PUBLISHED_DATE
;
