WITH SUBSTRING AS (
      SELECT SUBSTR(PRODUCT_CODE, 1, 2) CATEGORY,
             COUNT(*) PRODUCTS
        FROM PRODUCT
    GROUP BY SUBSTR(PRODUCT_CODE, 1, 2)
)
  SELECT CATEGORY,
         PRODUCTS
    FROM SUBSTRING
ORDER BY CATEGORY
;
