WITH SUB AS(
      SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
       WHERE START_DATE >= DATE '2022-08-01'
         AND START_DATE <= DATE '2022-10-31'
    GROUP BY CAR_ID
      HAVING COUNT(CAR_ID) >= 5
)
  SELECT TO_NUMBER(TO_CHAR(C.START_DATE, 'MM')) MONTH,
         C.CAR_ID, 
         COUNT(C.CAR_ID) RECORD
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY C
    JOIN SUB S
      ON C.CAR_ID = S.CAR_ID
   WHERE C.START_DATE >= DATE '2022-08-01'
     AND C.START_DATE <= DATE '2022-10-31'
GROUP BY TO_CHAR(C.START_DATE, 'MM'), C.CAR_ID
  HAVING COUNT(*)> 0
ORDER BY TO_CHAR(C.START_DATE, 'MM'), 
         C.CAR_ID DESC
;
