  SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR,
         EXTRACT(MONTH FROM SALES_DATE) MONTH,
         COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
         ROUND(
             (COUNT(DISTINCT O.USER_ID) 
             / (SELECT COUNT(DISTINCT USER_ID) 
                  FROM USER_INFO
                 WHERE EXTRACT(YEAR FROM JOINED) = 2021)), 1) PURCHASED_RATIO
    FROM ONLINE_SALE O
    JOIN USER_INFO U
      ON O.USER_ID = U.USER_ID
   WHERE EXTRACT(YEAR FROM JOINED) = 2021
GROUP BY EXTRACT(YEAR FROM SALES_DATE)
         , EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR
         , MONTH
;
