WITH JOINTABLE AS (
    SELECT AO.ANIMAL_ID, 
           AO.NAME, 
           AI.DATETIME DATETIME_IN,
           AO.DATETIME DATETIME_OUT
      FROM ANIMAL_OUTS AO
      JOIN ANIMAL_INS AI
        ON AO.ANIMAL_ID=AI.ANIMAL_ID
)
  SELECT ANIMAL_ID, NAME
    FROM JOINTABLE
   WHERE DATETIME_IN>DATETIME_OUT
ORDER BY DATETIME_IN
;
