WITH RENTED AS(
    SELECT CAR_ID
           , '대여중' AVAILABILITY
      FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
     WHERE START_DATE <= DATE '2022-10-16' 
       AND END_DATE >= DATE '2022-10-16'
),
DISTINCT_DATA AS(
    SELECT DISTINCT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
)
   SELECT D.CAR_ID
          , NVL(R.AVAILABILITY, '대여 가능') AVAILABILITY
     FROM DISTINCT_DATA D
LEFT JOIN RENTED R
       ON D.CAR_ID = R.CAR_ID
 ORDER BY CAR_ID DESC
;
