WITH CONDITIONS AS(
      SELECT USER_ID, 
             SUM(PRICE) TOTAL_SALES
        FROM USED_GOODS_BOARD UGB
        JOIN USED_GOODS_USER UGS
          ON UGB.WRITER_ID = UGS.USER_ID
       WHERE STATUS = 'DONE'
    GROUP BY USER_ID
      HAVING SUM(PRICE) >= 700000
    ORDER BY TOTAL_SALES
)
SELECT C.USER_ID, 
       U.NICKNAME, 
       C.TOTAL_SALES
  FROM CONDITIONS C
  JOIN USED_GOODS_USER U
    ON C.USER_ID = U.USER_ID
;
