  SELECT USER_ID
      , NICKNAME
      , CITY || ' ' || STREET_ADDRESS1 || ' ' || STREET_ADDRESS2 AS "전체주소"
      , SUBSTR(TLNO, 1, 3) || '-' || SUBSTR(TLNO, 4, 4) || '-' || SUBSTR(TLNO, 8, 4) AS "전화번호"
    FROM USED_GOODS_USER UGU
   WHERE (SELECT COUNT(BOARD_ID)
            FROM USED_GOODS_BOARD UGB
           WHERE UGB.WRITER_ID = UGU.USER_ID
         ) >= 3
ORDER BY USER_ID DESC
;
