WITH CONDITION1 AS
(
    SELECT USER_ID
      FROM USER_INFO
     WHERE EXTRACT(YEAR FROM JOINED) = 2021
)
  SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR,
         EXTRACT(MONTH FROM SALES_DATE) AS MONTH,
         COUNT(DISTINCT O.USER_ID) AS PURCHASED_USERS,
         ROUND(
             (COUNT(DISTINCT O.USER_ID) 
             / (SELECT COUNT(*) FROM CONDITION1)), 1) PURCHASED_RATIO
    FROM ONLINE_SALE O
    JOIN CONDITION1 C 
      ON O.USER_ID = C.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE)
         , EXTRACT(MONTH FROM SALES_DATE)
ORDER BY YEAR
         , MONTH
;
