WITH CONDITION AS 
(
    SELECT MEMBER_ID
      FROM
    (
          SELECT MEMBER_ID
                 , COUNT(MEMBER_ID)
            FROM REST_REVIEW
        GROUP BY MEMBER_ID
        ORDER BY COUNT(MEMBER_ID) DESC
    )
     WHERE ROWNUM = 1
)
SELECT
(
    SELECT MEMBER_NAME 
      FROM MEMBER_PROFILE 
     WHERE MEMBER_ID = (SELECT * FROM CONDITION)
) MEMBER_NAME
, REVIEW_TEXT
, TO_CHAR(REVIEW_DATE, 'YYYY-MM-DD') REVIEW_DATE
    FROM REST_REVIEW
   WHERE MEMBER_ID = (SELECT * FROM CONDITION)
ORDER BY REVIEW_DATE
         , REVIEW_TEXT
;
