  SELECT EXTRACT(YEAR FROM SALES_DATE) YEAR
         , EXTRACT(MONTH FROM SALES_DATE) MONTH
         , GENDER
         , COUNT(DISTINCT U.USER_ID) USERS
    FROM (SELECT * FROM USER_INFO WHERE GENDER IS NOT NULL) U
    JOIN ONLINE_SALE O
      ON U.USER_ID = O.USER_ID
GROUP BY EXTRACT(YEAR FROM SALES_DATE) 
         , EXTRACT(MONTH FROM SALES_DATE)
         , GENDER
ORDER BY YEAR
         , MONTH
         , GENDER
;
