  SELECT DISTINCT CP1.CART_ID
    FROM CART_PRODUCTS CP1
   WHERE CP1.NAME = 'Milk'
     AND EXISTS(
            SELECT 1
              FROM CART_PRODUCTS CP2
             WHERE CP2.NAME = 'Yogurt'
               AND CP2.CART_ID = CP1.CART_ID
         )
ORDER BY CP1.CART_ID
;
