WITH TOTAL_TABLE AS (
    SELECT FLAVOR
           , TOTAL_ORDER
    FROM FIRST_HALF
    UNION
    SELECT FLAVOR
           , TOTAL_ORDER
    FROM JULY
)
SELECT FLAVOR
  FROM
(
      SELECT SUM(TOTAL_ORDER)
             , FLAVOR
        FROM TOTAL_TABLE
    GROUP BY FLAVOR
    ORDER BY SUM(TOTAL_ORDER) DESC
)
 WHERE ROWNUM <= 3
;
