WITH TOTALDATE AS(
    SELECT P.PRODUCT_CODE, 
           P.PRICE, 
           O.SALES_AMOUNT
      FROM PRODUCT P
      JOIN OFFLINE_SALE O
        ON P.PRODUCT_ID = O.PRODUCT_ID 
)
  SELECT PRODUCT_CODE, 
         SUM(PRICE * SALES_AMOUNT) SALES
    FROM TOTALDATE
GROUP BY PRODUCT_CODE
ORDER BY SALES DESC, 
         PRODUCT_CODE
;
