WITH SUB AS (
    SELECT TO_CHAR(DATETIME, 'FMHH24') HOUR
      FROM ANIMAL_OUTS
     WHERE TO_NUMBER(TO_CHAR(DATETIME, 'FMHH24')) BETWEEN 9 AND 19
)
  SELECT HOUR, 
         COUNT(HOUR) COUNT
    FROM SUB
GROUP BY HOUR
ORDER BY TO_NUMBER(HOUR)
;
