  SELECT TO_CHAR(DATETIME, 'FMHH24') HOUR, 
         COUNT(*) COUNT
    FROM ANIMAL_OUTS
GROUP BY TO_CHAR(DATETIME, 'FMHH24')
  HAVING TO_CHAR(DATETIME, 'FMHH24') >= 9 
     AND TO_CHAR(DATETIME, 'FMHH24') < 20
ORDER BY TO_NUMBER(TO_CHAR(DATETIME, 'FMHH24'))
;
